### ISSUE TITLE
No errors, but the plugin doesn't do anything at all

### ISSUE THREAD

**Issue by TheDragonRing** [BoxOfDevs/DisableCMDS#2]
Exactly what title says, the plugin doesn't do anything at all, but there are no errors

**Comment by applqpak** [comment]
Lol..

**Comment by remotevase** [comment]
I get this same in EasyCMD and AuthEasy. I dont know why that happens... SOO ANNOYING!

**Comment by TheDragonRing** [comment]
Ikr, why does it have to happen!

**Comment by applqpak** [comment]
Just, lol.

**Comment by Taki21** [comment]
okay fine xD

**Comment by TheDragonRing** [comment]
XD

**Comment by Taki21** [comment]
when i have time then xD
i know In Array works but just in case i might change and see if it works but if not we leave in array

**Comment by TheDragonRing** [comment]
Ok

**Comment by Ad5001** [comment]
Resolved. Just check last commit

**Comment by TheDragonRing** [comment]
Ok thx, LOL I'll do some more stuff on it later, it's not quite finished yet :P
